# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: PR (created/updated)

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: set up go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ vars.GO_VERSION }}
    
    - name: test
      run: go test --timeout ${{ vars.GO_TEST_TIMEOUT }} -v ./...

    - name: build
      run: go build -v -o lxc ./cmd/main.go
